#!/usr/bin/env node

/**
 * Task Replayer
 *
 * Replays a recorded click task JSON generated by record-clicks.js.
 *
 * Usage:
 *   node other-task/recorder-task/replay-task.js <task.json> [options]
 *   node other-task/recorder-task/replay-task.js output/recorder/example.json
 *   node other-task/recorder-task/replay-task.js output/recorder/example.json --profile 1
 *   node other-task/recorder-task/replay-task.js output/recorder/example.json --speed 2
 *   node other-task/recorder-task/replay-task.js output/recorder/example.json --headless
 */

const { chromium } = require('patchright');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const PROJECT_ROOT = path.resolve(__dirname, '../..');

function parseArgs() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
    console.log([
      'Task Replayer',
      '',
      'Replays a recorded click task JSON.',
      '',
      'Usage:',
      '  node other-task/recorder-task/replay-task.js <task.json> [options]',
      '',
      'Options:',
      '  --profile <id>    Browser profile to use (default: 1)',
      '  --speed <factor>  Playback speed multiplier (default: 1, use 0 to skip delays)',
      '  --headless        Run in headless mode',
      '  --timeout <ms>    Element wait timeout in ms (default: 10000)',
      '  --help, -h        Show this help',
      '',
      'Examples:',
      '  node other-task/recorder-task/replay-task.js output/recorder/my-task.json',
      '  node other-task/recorder-task/replay-task.js output/recorder/my-task.json --speed 2',
      '  node other-task/recorder-task/replay-task.js output/recorder/my-task.json --speed 0 --headless',
    ].join('\n'));
    process.exit(0);
  }

  const taskPath = path.resolve(args[0]);
  let profileId = '1';
  let speed = 1;
  let headless = false;
  let timeout = 10000;

  for (let i = 1; i < args.length; i++) {
    if (args[i] === '--profile' && args[i + 1]) { profileId = args[++i]; continue; }
    if (args[i] === '--speed' && args[i + 1]) { speed = parseFloat(args[++i]); continue; }
    if (args[i] === '--headless') { headless = true; continue; }
    if (args[i] === '--timeout' && args[i + 1]) { timeout = parseInt(args[++i], 10); continue; }
  }

  return { taskPath, profileId, speed, headless, timeout };
}

async function main() {
  const { taskPath, profileId, speed, headless, timeout } = parseArgs();

  if (!fs.existsSync(taskPath)) {
    console.error(`❌ Task file not found: ${taskPath}`);
    process.exit(1);
  }

  const task = JSON.parse(fs.readFileSync(taskPath, 'utf8'));

  if (!task.actions || task.actions.length === 0) {
    console.error('❌ Task has no actions to replay');
    process.exit(1);
  }

  const profileDir = path.join(PROJECT_ROOT, 'browser-profiles', `browser-${profileId}`);
  if (!fs.existsSync(profileDir)) {
    console.error(`❌ Browser profile not found: ${profileDir}`);
    console.error(`   Run \`npm run browser ${profileId}\` first to create and log in.`);
    process.exit(1);
  }

  console.log('');
  console.log('╔═══════════════════════════════════════════════════════════╗');
  console.log('║          ▶️  Task Replayer                                ║');
  console.log('╠═══════════════════════════════════════════════════════════╣');
  console.log(`║  Task:      ${(task.name || 'unnamed').slice(0, 46).padEnd(46)} ║`);
  console.log(`║  URL:       ${task.url.slice(0, 46).padEnd(46)} ║`);
  console.log(`║  Actions:   ${String(task.actions.length).padEnd(46)} ║`);
  console.log(`║  Speed:     ${(speed === 0 ? 'instant' : speed + 'x').padEnd(46)} ║`);
  console.log(`║  Profile:   ${String(profileId).padEnd(46)} ║`);
  console.log(`║  Headless:  ${String(headless).padEnd(46)} ║`);
  console.log('╚═══════════════════════════════════════════════════════════╝');
  console.log('');

  const context = await chromium.launchPersistentContext(profileDir, {
    channel: 'chrome',
    headless,
  });

  const page = context.pages()[0] || await context.newPage();
  page.setDefaultTimeout(timeout);

  try {
    console.log(`🌐 Navigating to ${task.url}...`);
    await page.goto(task.url, { waitUntil: 'domcontentloaded', timeout: 60000 });
    await page.waitForTimeout(2000);

    let successCount = 0;
    let failCount = 0;

    for (let i = 0; i < task.actions.length; i++) {
      const action = task.actions[i];

      // Apply delay
      if (action.delayMs > 0 && speed !== 0) {
        const delay = Math.round(action.delayMs / speed);
        await page.waitForTimeout(delay);
      }

      const label = `[${i + 1}/${task.actions.length}]`;

      if (action.type === 'click') {
        try {
          // If the action was recorded on a different URL, navigate first
          if (action.url && action.url !== page.url()) {
            const actionOrigin = new URL(action.url).origin + new URL(action.url).pathname;
            const currentOrigin = new URL(page.url()).origin + new URL(page.url()).pathname;
            if (actionOrigin !== currentOrigin) {
              console.log(`${label} 🌐 Navigate: ${action.url}`);
              await page.goto(action.url, { waitUntil: 'domcontentloaded', timeout: 30000 });
              await page.waitForTimeout(1000);
            }
          }

          await page.waitForSelector(action.selector, { state: 'visible', timeout });
          await page.click(action.selector);
          const textHint = action.text ? ` "${action.text.slice(0, 30)}"` : '';
          console.log(`${label} ✅ Click: ${action.selector}${textHint}`);
          successCount++;
        } catch (err) {
          console.error(`${label} ❌ Click failed: ${action.selector} — ${err.message}`);
          failCount++;
        }
      }
    }

    console.log('');
    console.log('Replay Summary');
    console.log('==============');
    console.log(`Success: ${successCount}/${task.actions.length}`);
    if (failCount > 0) {
      console.log(`Failed:  ${failCount}/${task.actions.length}`);
      process.exitCode = 1;
    }

    // Keep browser open briefly so user can see the result
    if (!headless) {
      console.log('');
      console.log('⏳ Browser will stay open for 5 seconds...');
      await page.waitForTimeout(5000);
    }
  } finally {
    await context.close().catch(() => {});
  }
}

main().catch((err) => {
  console.error(`❌ Fatal: ${err.message}`);
  process.exit(1);
});
